-- =====================================================================
-- Migration: 0033_init_transcription_fallback_queue
-- Ticket:    JEBV4-126 (AUDIT-A IN-MEM-LIVE) durability follow-up
-- Purpose:   Durable backing store for the gateway's voice-note
--            transcription FALLBACK queue, which used to live ONLY in
--            gateway process memory (InMemoryTranscriptionFallbackQueue,
--            a ConcurrentQueue) and so LOST every pending retry job on
--            each restart / replica move — and with it the
--            PendingQueueDepth that drives the Whisper health check and
--            the transcription status endpoint (they silently reset to 0).
--
--            transcription_fallback_queue  (ITranscriptionFallbackQueue,
--              InMemoryTranscriptionFallbackQueue → PostgresTranscriptionFallbackQueue)
--            Holds the SMALL metadata rows for audio whose transcription
--            fell back — Whisper exhausted its retries / the breaker was
--            open AND the secondary provider was unavailable — that must
--            be re-driven once Whisper recovers. A queued job is just
--            (audio_id, reason, queued_at); the raw audio BYTES are NOT
--            stored here (large blobs do not belong in the gateway DB —
--            they are the voice-transcription-service / object-storage
--            concern; see IAudioStore, kept an intentional transient
--            in-gateway buffer, not a store of record).
--
--            This is gateway-OWNED reliability plumbing (the gateway is the
--            transcription composer for the MVP Whisper seam — there is no
--            upstream queue service that owns it yet), so its durable home
--            is gateway Postgres, alongside the push-reliability queues
--            (migration 0031) and the other AUDIT-A durability tables.
--
-- Notes:     Idempotent — CREATE TABLE/INDEX IF NOT EXISTS only, no seed
--            data (this is a runtime queue, not reference data), so
--            re-running is a no-op and never disturbs in-flight rows.
--            Column shapes mirror the in-memory QueuedTranscription record
--            byte-for-byte: audio_id / reason are TEXT, queued_at is
--            TIMESTAMPTZ (DateTimeOffset), id is a surrogate insertion-order
--            key so Snapshot() reads rows back in enqueue order.
-- Refs:      JEBV4-126 (TranscriptionFallbackQueue), T-backend-036 (Whisper
--            resilience policy — retry/backoff/breaker/fallback/enqueue).
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- transcription_fallback_queue — JEBV4-126
--   Append-on-fallback, read-back-for-depth queue of transcription jobs
--   awaiting a re-drive once Whisper recovers. Metadata only — no audio.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS transcription_fallback_queue (
    id         BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audio_id   TEXT          NOT NULL,
    reason     TEXT          NOT NULL DEFAULT '',
    queued_at  TIMESTAMPTZ   NOT NULL,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- Snapshot()/depth read path: rows returned in insertion order (id), and a
-- chronological probe by enqueue time for future drain-by-age policies.
CREATE INDEX IF NOT EXISTS idx_transcription_fallback_queued_at
    ON transcription_fallback_queue (queued_at);

INSERT INTO schema_migrations (version)
VALUES ('0033_init_transcription_fallback_queue')
ON CONFLICT (version) DO NOTHING;

COMMIT;
