namespace JeebGateway.Services.Clients;

/// <summary>
/// Typed proxy over the <c>cdn-service</c> — the fleet asset/object store the
/// gateway uses to persist and serve binary artifacts (signed Terms-of-Service
/// PDFs, generated earnings statements, KYC/dispute evidence) behind
/// short-lived signed URLs. Wired behind <c>FeatureFlags:UseUpstream:Cdn</c>.
///
/// <para>
/// DEPLOYMENT STATUS (read before touching the wiring). As of 2026-06-02
/// cdn-service is NOT yet on the swarm — there is NO live upstream. Its
/// <c>Services:Cdn:BaseUrl</c> in <c>appsettings.Production.json</c> is a
/// clearly-marked PLACEHOLDER (<c>http://192.168.2.50:PORT_TBD/</c>) pending
/// deployment; the feature flag is therefore DEFAULT-OFF in every environment
/// so the gateway never dials an unroutable host. When cdn-service ships:
///   1. set <c>Services:Cdn:BaseUrl</c> to the real swarm host:port,
///   2. add a readiness probe in <see cref="JeebGateway.Extensions.HealthCheckExtensions"/>
///      (liveness-only until then — see rule 2 there), and
///   3. flip <c>FeatureFlags:UseUpstream:Cdn = true</c> in
///      <c>appsettings.Production.json</c>.
/// Until then the consuming controller returns 503 (flag off), exactly the
/// remote-user-preferences kill-switch shape.
/// </para>
///
/// <para>
/// TICKETS SERVED. This seam exists to satisfy JEB-527, JEB-519, and JEB-59:
/// persist earnings statements and signed-ToS PDFs to durable object storage
/// with a 90-day retention window, and hand the mobile client a short-lived
/// signed URL to download them rather than streaming bytes through the gateway.
/// The gateway owns PDF GENERATION (<see cref="JeebGateway.Financials.IEarningsPdfGenerator"/>,
/// <see cref="JeebGateway.Financials.ReceiptGenerator"/>); cdn-service owns
/// durable STORAGE + signed delivery. This client is the storage transport only.
/// </para>
///
/// <para>
/// CONTRACT NOTE. cdn-service exposes no reachable OpenAPI document yet (the
/// service is not deployed), so this is a HAND-CODED minimal client over the
/// endpoints the tickets require — following the <see cref="IOfferServiceClient"/>
/// / <see cref="IBanServiceClient"/> precedent for upstreams without an NSwag
/// spec. When cdn-service publishes a Swashbuckle/OpenAPI doc, regenerate via
/// the NSwag pipeline (<c>scripts/regenerate-clients.sh</c>) and keep this
/// interface as the gateway-facing seam.
/// </para>
///
/// The named "cdn" HttpClient (registered in
/// <see cref="JeebGateway.Extensions.ServiceClientExtensions"/>) supplies the
/// BaseAddress (<c>Services:Cdn:BaseUrl</c>) + the org-standard bearer /
/// X-Service-Auth / resilience pipeline; this class never thinks about
/// retry/timeout/circuit-breaker.
///
/// All methods throw <see cref="HttpRequestException"/> on non-2xx.
/// </summary>
public interface ICDNServiceClient
{
    /// <summary>
    /// Uploads a binary asset to cdn-service via <c>POST /api/v1/assets</c>
    /// (multipart). Used to persist signed-ToS PDFs and generated earnings
    /// statements. The <see cref="CdnUploadRequest.RetentionDays"/> hint pins
    /// the 90-day retention window the tickets require (JEB-59); cdn-service
    /// is the record-of-truth for expiry.
    /// </summary>
    Task<CdnAsset> UploadAsync(CdnUploadRequest request, CancellationToken ct);

    /// <summary>
    /// Mints a short-lived signed download URL for a stored asset via
    /// <c>GET /api/v1/assets/{assetId}/signed-url?ttlSeconds=...</c>. The mobile
    /// client downloads directly from cdn-service; bytes never re-stream through
    /// the gateway (JEB-519).
    /// </summary>
    Task<CdnSignedUrl> GetSignedUrlAsync(
        string assetId,
        int ttlSeconds,
        CancellationToken ct);

    /// <summary>
    /// Brokers a short-lived signed <b>PUT</b> upload URL via
    /// <c>POST /api/v1/assets/upload-url</c> (DEC1, S03 H2/H3). The gateway
    /// pre-registers an asset slot (no bytes) and hands the mobile client a
    /// signed PUT target + the durable <c>object_ref</c>; the client uploads the
    /// bytes <b>directly</b> to cdn-service (H2b), never through the gateway. The
    /// returned <see cref="CdnUploadTicket.ExpiresInSeconds"/> is bounded
    /// (≤ 300s, BR-2) by cdn-service; the gateway clamps the requested TTL before
    /// the call as defence-in-depth.
    /// </summary>
    Task<CdnUploadTicket> MintUploadUrlAsync(
        CdnUploadUrlRequest request,
        CancellationToken ct);

    /// <summary>
    /// Reads an asset's metadata (content type, size, retention/expiry) via
    /// <c>GET /api/v1/assets/{assetId}</c>. Returns <c>null</c> on 404 (asset
    /// expired out of the retention window or never existed).
    /// </summary>
    Task<CdnAsset?> GetAssetAsync(string assetId, CancellationToken ct);
}

/// <summary>
/// Gateway-side upload input. Carries the already-generated bytes plus the
/// classification cdn-service needs to enforce retention and access scope.
/// </summary>
public sealed class CdnUploadRequest
{
    /// <summary>Raw asset bytes (e.g. the rendered PDF).</summary>
    public required byte[] Content { get; init; }

    /// <summary>Suggested file name surfaced in the signed-download response.</summary>
    public required string FileName { get; init; }

    /// <summary>MIME type, e.g. <c>application/pdf</c>.</summary>
    public required string ContentType { get; init; }

    /// <summary>
    /// Logical bucket / asset kind, e.g. <c>tos-signed</c>, <c>earnings-statement</c>,
    /// <c>kyc-evidence</c>. cdn-service uses this for access scoping.
    /// </summary>
    public required string Category { get; init; }

    /// <summary>
    /// Owning user id, so cdn-service can scope signed-URL access to the owner.
    /// </summary>
    public required string OwnerUserId { get; init; }

    /// <summary>
    /// Retention window in days. Tickets require 90-day retention for ToS /
    /// earnings artifacts (JEB-59); defaulted to 90.
    /// </summary>
    public int RetentionDays { get; init; } = 90;
}

/// <summary>Mirror of cdn-service's stored-asset metadata.</summary>
public sealed class CdnAsset
{
    public string? AssetId { get; init; }
    public string? FileName { get; init; }
    public string? ContentType { get; init; }
    public long SizeBytes { get; init; }
    public string? Category { get; init; }
    public string? OwnerUserId { get; init; }
    public DateTimeOffset CreatedAt { get; init; }

    /// <summary>When the asset ages out of the retention window.</summary>
    public DateTimeOffset? ExpiresAt { get; init; }
}

/// <summary>Mirror of cdn-service's signed-URL response.</summary>
public sealed class CdnSignedUrl
{
    public required string Url { get; init; }
    public DateTimeOffset ExpiresAt { get; init; }
}

/// <summary>
/// Gateway-side request to broker a signed PUT upload URL (DEC1). Carries only
/// the slot classification + MIME type and the owning user — no bytes. The
/// signed PUT target lets the mobile client upload directly to cdn-service.
/// </summary>
public sealed class CdnUploadUrlRequest
{
    /// <summary>
    /// Logical document slot, e.g. <c>id_document_front</c>, <c>id_document_back</c>,
    /// <c>vehicle_registration</c>, <c>selfie_with_liveness</c>. cdn-service uses
    /// this for access scoping + retention class.
    /// </summary>
    public required string Slot { get; init; }

    /// <summary>MIME type of the bytes the client will PUT, e.g. <c>image/jpeg</c>.</summary>
    public required string ContentType { get; init; }

    /// <summary>Owning user id, so cdn-service scopes the signed PUT to the owner.</summary>
    public required string OwnerUserId { get; init; }

    /// <summary>Requested signed-URL TTL in seconds (clamped to ≤ 300, BR-2).</summary>
    public int TtlSeconds { get; init; } = 300;

    /// <summary>Retention window in days for the eventual asset (default 90).</summary>
    public int RetentionDays { get; init; } = 90;
}

/// <summary>
/// Mirror of cdn-service's signed-PUT broker response (DEC1). The
/// <see cref="UploadUrl"/> is the signed PUT target; <see cref="ObjectRef"/> is
/// the durable reference the KYC submission records.
/// </summary>
public sealed class CdnUploadTicket
{
    /// <summary>Signed PUT URL the client uploads bytes to directly (H2b).</summary>
    public required string UploadUrl { get; init; }

    /// <summary>Durable object reference recorded in the KYC submission.</summary>
    public required string ObjectRef { get; init; }

    /// <summary>Seconds until the signed PUT URL expires (≤ 300, BR-2).</summary>
    public int ExpiresInSeconds { get; init; }
}
