//----------------------
// <auto-generated>
//     D2 wiring — typed-client surface for the review-report/moderation write added to
//     the SHARED, product-agnostic feedback-service (feedback-service PR #15:
//     POST /Review/report, idempotent per (ReviewId, ReporterId) → 202 Accepted,
//     400 validation, 500 failure). Authored in the NSwag-generated namespace + style as
//     a `partial` extension of the existing generated ServiceFeedbackClient, exactly as
//     ServiceFeedbackClient.RateeReviews.cs / ServiceFeedbackClient.BlindRatings.cs.
//
//     HONESTY / GR4 NOTE: hand-authored extension that faithfully mirrors the NSwag
//     output shape (same client, same ApiException, same Newtonsoft settings) so the
//     gateway consumes the upstream ONLY via the typed client. The canonical
//     regeneration from feedback-service's updated OpenAPI is DEFERRED to the repo's
//     NSwag freshness CI gate; locally there is no nswag toolchain. When the contract
//     is regenerated this file is superseded by the generated operation.
// </auto-generated>
//----------------------

#pragma warning disable 108
#pragma warning disable 114
#pragma warning disable 472
#pragma warning disable 612
#pragma warning disable 1573
#pragma warning disable 1591
#pragma warning disable 8073
#pragma warning disable 8603
#pragma warning disable 8604
#pragma warning disable 8625

namespace JeebGateway.service.ServiceFeedback
{
    using System = global::System;

    public partial class ServiceFeedbackClient
    {
        /// <summary>
        /// Report a review for moderation. The feedback-service is the OWNER/PROCESSOR of
        /// review reports; the gateway only forwards opaque identifiers. Real path:
        /// <c>POST /Review/report</c> with body <c>{ ReviewId, ReporterId, Reason? }</c>.
        /// Idempotent per <c>(ReviewId, ReporterId)</c>; a successful accept is 202.
        /// </summary>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task ReportReviewAsync(System.Guid reviewId, System.Guid reporterId, string? reason)
        {
            return ReportReviewAsync(reviewId, reporterId, reason, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task ReportReviewAsync(System.Guid reviewId, System.Guid reporterId, string? reason, System.Threading.CancellationToken cancellationToken)
        {
            var body = new ReportReviewRequest
            {
                ReviewId = reviewId,
                ReporterId = reporterId,
                Reason = reason,
            };

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    var json_ = Newtonsoft.Json.JsonConvert.SerializeObject(body, JsonSerializerSettings);
                    var content_ = new System.Net.Http.StringContent(json_);
                    content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json");
                    request_.Content = content_;
                    request_.Method = new System.Net.Http.HttpMethod("POST");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    var urlBuilder_ = new System.Text.StringBuilder();
                    if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                    // Operation Path: "Review/report"
                    urlBuilder_.Append("Review/report");

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ >= 200 && status_ < 300)
                        {
                            // 202 Accepted (or any 2xx) — the report was accepted for
                            // moderation. No response body is consumed.
                            return;
                        }
                        else
                        if (status_ == 400)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<ErrorResponse>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new ApiException<ErrorResponse>("Bad Request", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        if (status_ == 500)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<ErrorResponse>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new ApiException<ErrorResponse>("Internal Server Error", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }
    }

    /// <summary>
    /// Generic, product-agnostic review-report intent forwarded to feedback-service's
    /// <c>POST /Review/report</c>. Only opaque identifiers cross the boundary
    /// (GR2 — no product identities leak to the shared service). Mirrors
    /// feedback-service's report request contract 1:1.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ReportReviewRequest
    {
        [Newtonsoft.Json.JsonProperty("ReviewId", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Guid ReviewId { get; set; }

        [Newtonsoft.Json.JsonProperty("ReporterId", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Guid ReporterId { get; set; }

        [Newtonsoft.Json.JsonProperty("Reason", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Reason { get; set; }
    }
}

#pragma warning restore 108
#pragma warning restore 114
#pragma warning restore 472
#pragma warning restore 612
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
